### ISSUE TITLE
Size of the image?

### ISSUE THREAD

**Issue by lmariscal** [5zig/The-5zig-Mod-API-2.0#3]
Which is the maximum available size to send?

**Comment by 5zig** [comment]
Images can only be 64x64 pixels (at the moment) and have a size of max. Short.MAX_VALUE bytes (~32 kb).
Images are also being cached client-side, so that you don't get too much traffic from it. It is still recommended to cache the BufferedImage of the Image, so that the Server doesn't need to read the image from hard drive every time.

**Comment by 5zig** [comment]
Updated a few Java docs and improved Image sending.
If you find any bugs, open a New issue for Them please.
