### ISSUE TITLE
Craftbukkit 1.7 isn't supported

### ISSUE THREAD

**Issue by mattyokan** [5zig/The-5zig-Mod-API-2.0#5]
Hello,

during startup on the 1.7/1.8 Protocol hack:
22.04 11:27:06 [Server] INFO Enabling The5zigMod v2.3.2
22.04 11:27:06 [Server] INFO Trying to setup Hooks for CraftBukkit v1_7_R4
22.04 11:27:06 [Server] WARN java.lang.ClassNotFoundException: eu.the5zig.mod.server.util.protocol.BufferUtils_v1_7_R4
22.04 11:27:06 [Server] WARN at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
22.04 11:27:06 [Server] WARN at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101)
22.04 11:27:06 [Server] WARN at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86)
22.04 11:27:06 [Server] WARN at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
22.04 11:27:06 [Server] WARN at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
22.04 11:27:06 [Server] WARN at java.lang.Class.forName0(Native Method)
22.04 11:27:06 [Server] WARN at java.lang.Class.forName(Class.java:264)
22.04 11:27:06 [Server] WARN at eu.the5zig.mod.server.The5zigMod.setupHooks(The5zigMod.java:68)
22.04 11:27:06 [Server] WARN at eu.the5zig.mod.server.The5zigMod.onEnable(The5zigMod.java:39)
22.04 11:27:06 [Server] WARN at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316)
22.04 11:27:06 [Server] WARN at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332)
22.04 11:27:06 [Server] WARN at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:412)

It looks like 1.7 isn't supported with the API. Can you please add support for it? I went through the work to get a plugin developed for it and I can't use it without 1.7 support for the API.

**Comment by 5zig** [comment]
Will most likely never happen, sorry. Minecraft 1.7 has been released more than 3 and a half years ago and maintaining compatibility with it became very hard.
The biggest issue with Bukkit 1.7.x is that many Minecraft dependencies are in the net.minecraft package rather than the root of the jar as with all older Minecraft versions. Some classes of the API require these dependencies and thus cannot be compatible with both 1.7 and 1.8+ versions of Minecraft.
The API is open-source though, so feel free to alter it to your needs if you want. In theory, 1.7 support should not be too hard if you don't care about other Minecraft versions.
